import{a as m,S as p,i as n}from"./assets/vendor-5YrzWRhu.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const y="51471509-416a43bd25f243e05adcff326",g="https://pixabay.com/api/";async function h(s){const o={key:y,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0};try{return(await m.get(g,{params:o})).data}catch(r){throw new Error(r.message)}}const c=document.querySelector(".gallery"),b=new p(".gallery a",{captionsData:"alt",captionDelay:250});function L(s){const o=s.map(({webformatURL:r,largeImageURL:a,tags:e,likes:t,views:i,comments:f,downloads:u})=>{const d=e.split(",").slice(0,3).join(", ");return`
          <a class="gallery__item" href="${a}">
            <img class="gallery__image" src="${r}" alt="${d}" loading="lazy"/>
            <div class="gallery__info">
              <p class="info-item"><b>Likes:</b> ${t}</p>
              <p class="info-item"><b>Views:</b> ${i}</p>
              <p class="info-item"><b>Comments:</b> ${f}</p>
              <p class="info-item"><b>Downloads:</b> ${u}</p>
            </div>
          </a>
        `}).join("");c.innerHTML=o,b.refresh()}function q(){c.innerHTML=""}function w(){document.querySelector(".loader").classList.remove("is-hidden")}function S(){document.querySelector(".loader").classList.add("is-hidden")}const l=document.querySelector(".form"),_=l.querySelector('input[name="search-text"]');document.getElementById("loader");l.addEventListener("submit",async s=>{s.preventDefault();const o=_.value.trim();if(o===""){n.warning({message:"The search field cannot be empty",position:"topRight",backgroundColor:"#f57676ff"});return}q(),w();try{const r=await h(o);if(r.hits.length===0){n.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#f57676ff"});return}L(r.hits)}catch(r){n.error({message:"The request failed. Please try again later",position:"topRight",backgroundColor:"#f57676ff"}),console.error("API Error:",r)}finally{S()}});
//# sourceMappingURL=index.js.map
